name: craftcodepuntbe
recipe: wordpress
config:
  webroot: ./web
  php: '8.2'
  environment:
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
    MYSQL_ROOT_PASSWORD: rootpassword

tooling:
  npm:
    service: appserver
    cmd: npm
  vite:
    service: appserver
    cmd: npm run dev -- --host

services:
  myservice:
    type: phpmyadmin:5.2
    
  appserver:
    type: php:8.2
    build_as_root:
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs

proxy:
  appserver:
    - craftcodepuntbe.lndo.site

